language: python

env:
  matrix:
    - PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
    - PYTHON_VERSION="2.7" NUMPY_VERSION="1.9"
    - PYTHON_VERSION="3.3" NUMPY_VERSION="1.9"
    - PYTHON_VERSION="3.4" NUMPY_VERSION="1.9"
    - PYTHON_VERSION="3.4"

install:
    - source continuous_integration/install.sh

script:
    - make
