language: python

env:
  matrix:
    - PYTHON_VERSION="2.6" NUMPY_VERSION="1.6"
    - PYTHON_VERSION="2.7" NUMPY_VERSION="1.7"
    - PYTHON_VERSION="3.3" NUMPY_VERSION="1.8"
    - PYTHON_VERSION="3.4" NUMPY_VERSION="1.9"
    # NUMPY_VERSION not set means numpy is not installed
    - PYTHON_VERSION="3.4"
    - PYTHON_VERSION="3.5" NUMPY_VERSION="1.9" COVERAGE="true"

install:
    - source continuous_integration/install.sh

script:
    - make

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
